

[package]
name = "q3_server"
authors = ["C2Rust"]
version = "0.0.0"
publish = false
edition = "2018"
autobins = false

[[bin]]
name = "q3_server"
path = "lib.rs"


[dependencies]
c2rust-asm-casts = "0.1"
libc = "0.2"



